-- MySQL Script generated by MySQL Workbench
-- Tue Mar 19 22:53:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Alquiler-Vivienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Alquiler-Vivienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Alquiler-Vivienda` DEFAULT CHARACTER SET utf8 ;
USE `Alquiler-Vivienda` ;

-- -----------------------------------------------------
-- Table `Alquiler-Vivienda`.`PROPIETARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-Vivienda`.`PROPIETARIO` (
  `idPropietario` INT NOT NULL,
  `No. Telefono` VARCHAR(45) NULL,
  `Escritura` VARCHAR(45) NULL,
  PRIMARY KEY (`idPropietario`),
  UNIQUE INDEX `No. Telefono_UNIQUE` (`No. Telefono` ASC) VISIBLE,
  UNIQUE INDEX `Escritura_UNIQUE` (`Escritura` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-Vivienda`.`INQUILINO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-Vivienda`.`INQUILINO` (
  `idInquilino` INT NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  `Edad` VARCHAR(45) NULL,
  `Comprobante de Ingresos` VARCHAR(45) NULL,
  PRIMARY KEY (`idInquilino`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE,
  UNIQUE INDEX `Edad_UNIQUE` (`Edad` ASC) VISIBLE,
  UNIQUE INDEX `Comprobante de Ingresos_UNIQUE` (`Comprobante de Ingresos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-Vivienda`.`ALQUILER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-Vivienda`.`ALQUILER` (
  `idAlquiler` INT NOT NULL,
  `No. Inicio de pago` VARCHAR(45) NULL,
  `INQUILINO_idInquilino` INT NOT NULL,
  PRIMARY KEY (`idAlquiler`, `INQUILINO_idInquilino`),
  UNIQUE INDEX `No. Inicio de pago_UNIQUE` (`No. Inicio de pago` ASC) VISIBLE,
  INDEX `fk_ALQUILER_INQUILINO1_idx` (`INQUILINO_idInquilino` ASC) VISIBLE,
  CONSTRAINT `fk_ALQUILER_INQUILINO1`
    FOREIGN KEY (`INQUILINO_idInquilino`)
    REFERENCES `Alquiler-Vivienda`.`INQUILINO` (`idInquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-Vivienda`.`VIVIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-Vivienda`.`VIVIENDA` (
  `idVivienda` INT NOT NULL,
  `PROPIETARIO_idPropietario` INT NOT NULL,
  `ALQUILER_idAlquiler` INT NOT NULL,
  PRIMARY KEY (`idVivienda`, `PROPIETARIO_idPropietario`, `ALQUILER_idAlquiler`),
  INDEX `fk_VIVIENDA_PROPIETARIO1_idx` (`PROPIETARIO_idPropietario` ASC) VISIBLE,
  INDEX `fk_VIVIENDA_ALQUILER1_idx` (`ALQUILER_idAlquiler` ASC) VISIBLE,
  CONSTRAINT `fk_VIVIENDA_PROPIETARIO1`
    FOREIGN KEY (`PROPIETARIO_idPropietario`)
    REFERENCES `Alquiler-Vivienda`.`PROPIETARIO` (`idPropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIVIENDA_ALQUILER1`
    FOREIGN KEY (`ALQUILER_idAlquiler`)
    REFERENCES `Alquiler-Vivienda`.`ALQUILER` (`idAlquiler`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-Vivienda`.`DESCRIPCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-Vivienda`.`DESCRIPCION` (
  `Construccion` VARCHAR(45) NULL,
  `Cuartos` VARCHAR(45) NULL,
  `Baños` VARCHAR(45) NULL,
  `Pisos` VARCHAR(45) NULL,
  `VIVIENDA_idVivienda` INT NOT NULL,
  UNIQUE INDEX `Construccion_UNIQUE` (`Construccion` ASC) VISIBLE,
  UNIQUE INDEX `Cuartos_UNIQUE` (`Cuartos` ASC) VISIBLE,
  UNIQUE INDEX `Baños_UNIQUE` (`Baños` ASC) VISIBLE,
  UNIQUE INDEX `Pisos_UNIQUE` (`Pisos` ASC) VISIBLE,
  PRIMARY KEY (`VIVIENDA_idVivienda`),
  CONSTRAINT `fk_DESCRIPCION_VIVIENDA1`
    FOREIGN KEY (`VIVIENDA_idVivienda`)
    REFERENCES `Alquiler-Vivienda`.`VIVIENDA` (`idVivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-Vivienda`.`NOMBRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-Vivienda`.`NOMBRE` (
  `P.nombre` INT NULL,
  `S.nombre` VARCHAR(45) NULL,
  `A.paterno` VARCHAR(45) NULL,
  `A.materno` INT NULL,
  `INQUILINO_idInquilino` INT NOT NULL,
  UNIQUE INDEX `P.nombre_UNIQUE` (`P.nombre` ASC) VISIBLE,
  UNIQUE INDEX `S.nombre_UNIQUE` (`S.nombre` ASC) VISIBLE,
  UNIQUE INDEX `A.paterno_UNIQUE` (`A.paterno` ASC) VISIBLE,
  UNIQUE INDEX `A.materno_UNIQUE` (`A.materno` ASC) VISIBLE,
  PRIMARY KEY (`INQUILINO_idInquilino`),
  CONSTRAINT `fk_NOMBRE_INQUILINO1`
    FOREIGN KEY (`INQUILINO_idInquilino`)
    REFERENCES `Alquiler-Vivienda`.`INQUILINO` (`idInquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-Vivienda`.`DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-Vivienda`.`DIRECCION` (
  `Calle` VARCHAR(45) NULL,
  `No.ext` VARCHAR(45) NULL,
  `No.int` VARCHAR(45) NULL,
  `CP` VARCHAR(45) NULL,
  `Colonia` VARCHAR(45) NOT NULL,
  `VIVIENDA_idVivienda` INT NOT NULL,
  UNIQUE INDEX `Calle_UNIQUE` (`Calle` ASC) VISIBLE,
  UNIQUE INDEX `No.ext_UNIQUE` (`No.ext` ASC) VISIBLE,
  UNIQUE INDEX `No.int_UNIQUE` (`No.int` ASC) VISIBLE,
  UNIQUE INDEX `CP_UNIQUE` (`CP` ASC) VISIBLE,
  UNIQUE INDEX `Colonia_UNIQUE` (`Colonia` ASC) VISIBLE,
  PRIMARY KEY (`VIVIENDA_idVivienda`),
  CONSTRAINT `fk_DIRECCION_31`
    FOREIGN KEY (`VIVIENDA_idVivienda`)
    REFERENCES `Alquiler-Vivienda`.`VIVIENDA` (`idVivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-Vivienda`.`COMPROBANTE DE PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-Vivienda`.`COMPROBANTE DE PAGO` (
  `Folio` INT NULL,
  `Fecha de inico de contrato` VARCHAR(45) NULL,
  `ALQUILER_idAlquiler` INT NOT NULL,
  UNIQUE INDEX `Folio_UNIQUE` (`Folio` ASC) VISIBLE,
  PRIMARY KEY (`ALQUILER_idAlquiler`),
  CONSTRAINT `fk_COMPROBANTE DE PAGO_ALQUILER1`
    FOREIGN KEY (`ALQUILER_idAlquiler`)
    REFERENCES `Alquiler-Vivienda`.`ALQUILER` (`idAlquiler`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-Vivienda`.`SERVICIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-Vivienda`.`SERVICIOS` (
  `Servicio 1` VARCHAR(45) NULL,
  `Servicio 2` VARCHAR(45) NULL,
  `VIVIENDA_idVivienda` INT NOT NULL,
  UNIQUE INDEX `Servicio 1_UNIQUE` (`Servicio 1` ASC) VISIBLE,
  UNIQUE INDEX `Servicio 2_UNIQUE` (`Servicio 2` ASC) VISIBLE,
  PRIMARY KEY (`VIVIENDA_idVivienda`),
  CONSTRAINT `fk_SERVICIOS_VIVIENDA1`
    FOREIGN KEY (`VIVIENDA_idVivienda`)
    REFERENCES `Alquiler-Vivienda`.`VIVIENDA` (`idVivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alquiler-Vivienda`.`NOMBRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alquiler-Vivienda`.`NOMBRE` (
  `P.nombre` INT NULL,
  `S.nombre` VARCHAR(45) NULL,
  `A.paterno` VARCHAR(45) NULL,
  `A.materno` INT NULL,
  `INQUILINO_idInquilino` INT NOT NULL,
  UNIQUE INDEX `P.nombre_UNIQUE` (`P.nombre` ASC) VISIBLE,
  UNIQUE INDEX `S.nombre_UNIQUE` (`S.nombre` ASC) VISIBLE,
  UNIQUE INDEX `A.paterno_UNIQUE` (`A.paterno` ASC) VISIBLE,
  UNIQUE INDEX `A.materno_UNIQUE` (`A.materno` ASC) VISIBLE,
  PRIMARY KEY (`INQUILINO_idInquilino`),
  CONSTRAINT `fk_NOMBRE_INQUILINO1`
    FOREIGN KEY (`INQUILINO_idInquilino`)
    REFERENCES `Alquiler-Vivienda`.`INQUILINO` (`idInquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
